### ISSUE TITLE
[Bug]请问目前是否不支持postgre？以及快速开始的测试代码是否不支持更改表名？

### ISSUE THREAD

**Issue by NOCSF** [gaarason/database-all#50]
以下是postgre配置：
```yaml
spring:
  application:
    name: 'Laravel'
  datasource:
    url: jdbc:postgresql://localhost:5432/watchdog.ui.api
    username: postgres
    password: ****
    driver-class-name: org.postgresql.Driver
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
```
会出现以下报错：

![Image](https://github.com/user-attachments/assets/3f97c4f2-7c45-4f80-8017-b78a0bb44c1a)

---

以下是以mysql为驱动执行测试：
```yaml
spring:
  application:
    name: 'Laravel'
  datasource:
    url: jdbc:mysql://localhost:3306/watchdog.ui.api
    username: root
    password: ****
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
```

更改默认表名查询时，会出现如下报错：

![Image](https://github.com/user-attachments/assets/0d852866-81fa-4f56-a32e-1f29f331cfbf)

表结构如下：

![Image](https://github.com/user-attachments/assets/b04a8356-6e02-4595-b814-133a7dd2bcc6)
